name: Coti Crypto SDK Publisher

on:
  workflow_dispatch:
    branches:
      - dev
      - master
    inputs:
      version:
        type: choice
        description: Choose version
        required: true
        options:
          - prerelease
          - release
          - prepatch
          - preminor
          - premajor

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '12.22.4'
          registry-url: 'https://registry.npmjs.org'

      - name : Npm version
        run: |
          git config --local user.email "eli@coti.io"
          git config --local user.name "coti-tech"
          npm i
          npm run build
          npm run version-${{ inputs.version }}
          git log -3
